/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PantallaMetodos.java
 *
 * Created on 22-sep-2011, 18:39:29
 */

package Pantalla;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author diego
 */
public class PantallaParametros extends javax.swing.JDialog {

    /** Creates new form PantallaMetodos */
    
    public PantallaParametros(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoDeMetodos = new javax.swing.ButtonGroup();
        BotonCancelarParametros = new javax.swing.JButton();
        campoAlfa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoBeta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoGama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        botonGuardarParametros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Metodos de Suavizamiento");
        setAlwaysOnTop(true);

        BotonCancelarParametros.setText("Cancelar");

        jLabel2.setText("Alfa");

        jLabel3.setText("Beta");

        jLabel4.setText("Gama");

        botonGuardarParametros.setText("Guardar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonGuardarParametros)
                        .addGap(30, 30, 30)
                        .addComponent(BotonCancelarParametros))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel3))
                            .addComponent(jLabel4))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoGama)
                            .addComponent(campoBeta)
                            .addComponent(campoAlfa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoAlfa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoBeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoGama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardarParametros)
                    .addComponent(BotonCancelarParametros))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCancelarParametros;
    private javax.swing.JButton botonGuardarParametros;
    private javax.swing.JTextField campoAlfa;
    private javax.swing.JTextField campoBeta;
    private javax.swing.JTextField campoGama;
    private javax.swing.ButtonGroup grupoDeMetodos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    public JButton getBotonCancelarParametros() {
        return BotonCancelarParametros;
    }

    public void setBotonCancelarParametros(JButton BotonCancelarMetodos) {
        this.BotonCancelarParametros = BotonCancelarMetodos;
    }

    public JButton getBotonGuardarParametros() {
        return botonGuardarParametros;
    }

    public void setBotonGuardarParametros(JButton botonCalcularParametros) {
        this.botonGuardarParametros = botonCalcularParametros;
    }

    public JTextField getCampoAlfa() {
        return campoAlfa;
    }

    public void setCampoAlfa(JTextField campoAlfa) {
        this.campoAlfa = campoAlfa;
    }

    public JTextField getCampoBeta() {
        return campoBeta;
    }

    public void setCampoBeta(JTextField campoBeta) {
        this.campoBeta = campoBeta;
    }

    public JTextField getCampoGama() {
        return campoGama;
    }

    public void setCampoGama(JTextField campoGama) {
        this.campoGama = campoGama;
    }

    public ButtonGroup getGrupoDeMetodos() {
        return grupoDeMetodos;
    }

}
