/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PantallaMetodos.java
 *
 * Created on 22-sep-2011, 18:39:29
 */

package Pantalla;

import com.toedter.calendar.JDateChooser;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author malayo
 */
public class PantallaMetodos extends javax.swing.JDialog {

    /** Creates new form PantallaMetodos */
    
    public PantallaMetodos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoDeMetodos = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        BotonCancelarMetodos = new javax.swing.JButton();
        campoAlfa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        botonSimple = new javax.swing.JRadioButton();
        botonTendencia = new javax.swing.JRadioButton();
        botonEstacionalidad = new javax.swing.JRadioButton();
        campoBeta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoGama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        botonCalcularMetodos = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        comboProductos = new javax.swing.JComboBox();
        txFechadesde = new com.toedter.calendar.JDateChooser("dd/MM/yyyy", "####/##/##", '_');
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txFechahasta = new com.toedter.calendar.JDateChooser("dd/MM/yyyy", "####/##/##", '_');
        jLabel8 = new javax.swing.JLabel();
        txPeriodo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaResultado = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaResultado2 = new javax.swing.JTextArea();
        botonDE = new javax.swing.JCheckBox();
        botonSR = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Metodos de Suavizamiento");
        setAlwaysOnTop(true);

        jLabel1.setText("Metodos:");

        BotonCancelarMetodos.setText("Cancelar");

        jLabel2.setText("Alfa");

        grupoDeMetodos.add(botonSimple);
        botonSimple.setText("Simple");

        grupoDeMetodos.add(botonTendencia);
        botonTendencia.setText("Tendencia");

        grupoDeMetodos.add(botonEstacionalidad);
        botonEstacionalidad.setText("Estacionalidad");

        jLabel3.setText("Beta");

        jLabel4.setText("Gama");

        botonCalcularMetodos.setText("Calcular");

        jLabel5.setText("Productos:");

        jLabel6.setText("Fecha Desde");

        jLabel7.setText("Fecha Hasta");

        jLabel8.setText("Periodos a Predecir");

        txPeriodo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txPeriodoFocusGained(evt);
            }
        });

        areaResultado.setColumns(20);
        areaResultado.setRows(5);
        jScrollPane1.setViewportView(areaResultado);

        areaResultado2.setColumns(20);
        areaResultado2.setRows(5);
        jScrollPane2.setViewportView(areaResultado2);

        botonDE.setText("Desviación Estandar");

        botonSR.setText("Señal de rastreo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(botonCalcularMetodos)
                                        .addGap(39, 39, 39)
                                        .addComponent(BotonCancelarMetodos))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(botonEstacionalidad)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(15, 15, 15)
                                                        .addComponent(jLabel2))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(9, 9, 9)
                                                        .addComponent(jLabel3))
                                                    .addComponent(jLabel4))
                                                .addGap(20, 20, 20)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(campoGama)
                                                    .addComponent(campoBeta)
                                                    .addComponent(campoAlfa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(comboProductos, 0, 238, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(botonSimple)
                                                    .addComponent(botonTendencia))
                                                .addGap(149, 149, 149)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel7))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txFechadesde, 0, 0, Short.MAX_VALUE)
                                                    .addComponent(txFechahasta, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(21, 21, 21))))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonDE)
                        .addGap(18, 18, 18)
                        .addComponent(botonSR)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(comboProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(campoAlfa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(campoBeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(campoGama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BotonCancelarMetodos)
                                    .addComponent(botonCalcularMetodos)
                                    .addComponent(botonDE)
                                    .addComponent(botonSR)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonSimple)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonTendencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonEstacionalidad))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txFechadesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txFechahasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(txPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void txPeriodoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txPeriodoFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_txPeriodoFocusGained

    /**
    * @param args the command line arguments
    */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCancelarMetodos;
    private javax.swing.JTextArea areaResultado;
    private javax.swing.JTextArea areaResultado2;
    private javax.swing.JButton botonCalcularMetodos;
    private javax.swing.JCheckBox botonDE;
    private javax.swing.JRadioButton botonEstacionalidad;
    private javax.swing.JCheckBox botonSR;
    private javax.swing.JRadioButton botonSimple;
    private javax.swing.JRadioButton botonTendencia;
    private javax.swing.JTextField campoAlfa;
    private javax.swing.JTextField campoBeta;
    private javax.swing.JTextField campoGama;
    private javax.swing.JComboBox comboProductos;
    private javax.swing.ButtonGroup grupoDeMetodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser txFechadesde;
    private com.toedter.calendar.JDateChooser txFechahasta;
    private javax.swing.JTextField txPeriodo;
    // End of variables declaration//GEN-END:variables

    public JTextArea getAreaResultado2() {
        return areaResultado2;
    }

    public void setAreaResultado2(JTextArea areaResultado2) {
        this.areaResultado2 = areaResultado2;
    }

    public JCheckBox getBotonDE() {
        return botonDE;
    }

    public void setBotonDE(JCheckBox botonDE) {
        this.botonDE = botonDE;
    }

    public JCheckBox getBotonSR() {
        return botonSR;
    }

    public void setBotonSR(JCheckBox botonSR) {
        this.botonSR = botonSR;
    }

    public JTextArea getAreaResultado() {
        return areaResultado;
    }

    public void setAreaResultado(JTextArea areaResultado) {
        this.areaResultado = areaResultado;
    }

    public JDateChooser getTxFechadesde() {
        return txFechadesde;
    }

    public void setTxFechadesde(JDateChooser txFechadesde) {
        this.txFechadesde = txFechadesde;
    }

    public JDateChooser getTxFechahasta() {
        return txFechahasta;
    }

    public void setTxFechahasta(JDateChooser txFechahasta) {
        this.txFechahasta = txFechahasta;
    }

    public JTextField getTxPeriodo() {
        return txPeriodo;
    }

    public void setTxPeriodo(JTextField txPeriodo) {
        this.txPeriodo = txPeriodo;
    }

    public JComboBox getComboProductos() {
        return comboProductos;
    }

    public void setComboProductos(JComboBox comboProductos) {
        this.comboProductos = comboProductos;
    }

    public JButton getBotonCancelarMetodos() {
        return BotonCancelarMetodos;
    }

    public void setBotonCancelarMetodos(JButton BotonCancelarMetodos) {
        this.BotonCancelarMetodos = BotonCancelarMetodos;
    }

    public JButton getBotonCalcularMetodos() {
        return botonCalcularMetodos;
    }

    public void setBotonCalcularMetodos(JButton botonCalcularMetodos) {
        this.botonCalcularMetodos = botonCalcularMetodos;
    }

    public JRadioButton getBotonEstacionalidad() {
        return botonEstacionalidad;
    }

    public void setBotonEstacionalidad(JRadioButton botonEstacionalidad) {
        this.botonEstacionalidad = botonEstacionalidad;
    }

    public JRadioButton getBotonSimple() {
        return botonSimple;
    }

    public void setBotonSimple(JRadioButton botonSimple) {
        this.botonSimple = botonSimple;
    }

    public JRadioButton getBotonTendencia() {
        return botonTendencia;
    }

    public void setBotonTendencia(JRadioButton botonTendencia) {
        this.botonTendencia = botonTendencia;
    }

    public JTextField getCampoAlfa() {
        return campoAlfa;
    }

    public void setCampoAlfa(JTextField campoAlfa) {
        this.campoAlfa = campoAlfa;
    }

    public JTextField getCampoBeta() {
        return campoBeta;
    }

    public void setCampoBeta(JTextField campoBeta) {
        this.campoBeta = campoBeta;
    }

    public JTextField getCampoGama() {
        return campoGama;
    }

    public void setCampoGama(JTextField campoGama) {
        this.campoGama = campoGama;
    }

    public ButtonGroup getGrupoDeMetodos() {
        return grupoDeMetodos;
    }

    public void setGrupoDeMetodos(ButtonGroup grupoDeMetodos) {
        this.grupoDeMetodos = grupoDeMetodos;
    }

}
