/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PantallaRecibirPedido.java
 *
 * Created on 07-nov-2011, 10:28:48
 */
package Pantalla;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author duende
 */
public class PantallaRecibirPedido extends javax.swing.JInternalFrame {

    /** Creates new form PantallaRecibirPedido */
    public PantallaRecibirPedido() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcPedidoPendiente = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcProductosPedidos = new javax.swing.JComboBox();
        lbNroPedido = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jdFechaEntrega = new com.toedter.calendar.JDateChooser();
        jbAceptar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jtProveedor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtCantidadRecibida = new javax.swing.JTextField();
        jlDescripcion = new javax.swing.JLabel();

        setClosable(true);

        jLabel1.setText("Proveedor");

        jLabel2.setText("Producto");

        lbNroPedido.setText("Nro Pedido:");

        jLabel4.setText("Fecha Entrega");

        jbAceptar.setText("Aceptar");

        jbCancelar.setText("Cancelar");

        jLabel3.setText("Cant. Recibida");

        jlDescripcion.setFont(new java.awt.Font("Dialog", 0, 10));
        jlDescripcion.setText("descripcion...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lbNroPedido))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcPedidoPendiente, 0, 182, Short.MAX_VALUE)
                            .addComponent(jtProveedor)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jbAceptar)
                        .addGap(36, 36, 36)
                        .addComponent(jbCancelar)))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jcProductosPedidos, 0, 182, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlDescripcion)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtCantidadRecibida)
                        .addComponent(jdFechaEntrega, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbNroPedido)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jcPedidoPendiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcProductosPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlDescripcion)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtCantidadRecibida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jdFechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAceptar)
                    .addComponent(jbCancelar))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JComboBox jcPedidoPendiente;
    private javax.swing.JComboBox jcProductosPedidos;
    private com.toedter.calendar.JDateChooser jdFechaEntrega;
    private javax.swing.JLabel jlDescripcion;
    private javax.swing.JTextField jtCantidadRecibida;
    private javax.swing.JTextField jtProveedor;
    private javax.swing.JLabel lbNroPedido;
    // End of variables declaration//GEN-END:variables

    public JButton getJbAceptar() {
        return jbAceptar;
    }

    public void setJbAceptar(JButton jbAceptar) {
        this.jbAceptar = jbAceptar;
    }

    public JButton getJbCancelar() {
        return jbCancelar;
    }

    public void setJbCancelar(JButton jbCancelar) {
        this.jbCancelar = jbCancelar;
    }

    public JComboBox getJcPedidoPendiente() {
        return jcPedidoPendiente;
    }

    public void setJcPedidoPendiente(JComboBox jcPedidoPendiente) {
        this.jcPedidoPendiente = jcPedidoPendiente;
    }

    public JComboBox getJcProductosPedidos() {
        return jcProductosPedidos;
    }

    public void setJcProductosPedidos(JComboBox jcProductosPedidos) {
        this.jcProductosPedidos = jcProductosPedidos;
    }

    public JDateChooser getJdFechaEntrega() {
        return jdFechaEntrega;
    }

    public void setJdFechaEntrega(JDateChooser jdFechaEntrega) {
        this.jdFechaEntrega = jdFechaEntrega;
    }

    public JTextField getJtProveedor() {
        return jtProveedor;
    }

    public void setJtProveedor(JTextField jtProveedor) {
        this.jtProveedor = jtProveedor;
    }

    public JTextField getJtCantidadRecibida() {
        return jtCantidadRecibida;
    }

    public void setJtCantidadRecibida(JTextField jtCantidadRecibida) {
        this.jtCantidadRecibida = jtCantidadRecibida;
    }

    public JLabel getJlDescripcion() {
        return jlDescripcion;
    }

    public void setJlDescripcion(JLabel jlDescripcion) {
        this.jlDescripcion = jlDescripcion;
    }

    
}
