/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PantallaVenta.java
 *
 * Created on 18-sep-2011, 22:37:18
 */
package Pantalla;

import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JMenuItem;
import javax.swing.table.TableModel;

/**
 *
 * @author duende
 */
public class PantallaVenta extends javax.swing.JInternalFrame {

    /** Creates new form PantallaVenta */
    public PantallaVenta() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbSelecCliente = new javax.swing.JButton();
        jlCliente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDetalleVenta = new javax.swing.JTable();
        JbSelecProducto = new javax.swing.JButton();
        jtTotal = new javax.swing.JTextField();
        jbConfirma = new javax.swing.JButton();
        jbCancela = new javax.swing.JButton();
        Fecha = new javax.swing.JFormattedTextField();
        NroFactura = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mBuscar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximizable(true);
        setTitle("Seleccion");
        setAlignmentX(10.0F);
        setAlignmentY(10.0F);
        setAutoscrolls(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setEnabled(false);
        setName("Seleccion"); // NOI18N

        jbSelecCliente.setText("Cliente");

        jlCliente.setText("Seleccione un cliente");

        jtDetalleVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtDetalleVenta);

        JbSelecProducto.setText("Producto");

        jtTotal.setText("$");

        jbConfirma.setText("Confirmar");

        jbCancela.setText("Cancelar");

        Fecha.setText("--/--/----");

        NroFactura.setAlignmentX(2.5F);

        jLabel1.setText("Nro. Factura");

        jLabel2.setText("Fecha");

        jMenu1.setText("Menú");

        mBuscar.setText("buscar venta");
        jMenu1.add(mBuscar);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jbConfirma)
                        .addGap(35, 35, 35)
                        .addComponent(jbCancela))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(400, 400, 400)
                                .addComponent(jtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jbSelecCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(JbSelecProducto))
                                        .addGap(32, 32, 32)
                                        .addComponent(jlCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(107, 107, 107))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(44, 44, 44)
                                        .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1)
                                        .addGap(29, 29, 29)
                                        .addComponent(NroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSelecCliente)
                    .addComponent(jlCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JbSelecProducto)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbConfirma)
                    .addComponent(jbCancela))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Fecha;
    private javax.swing.JButton JbSelecProducto;
    private javax.swing.JFormattedTextField NroFactura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCancela;
    private javax.swing.JButton jbConfirma;
    private javax.swing.JButton jbSelecCliente;
    private javax.swing.JLabel jlCliente;
    private javax.swing.JTable jtDetalleVenta;
    private javax.swing.JTextField jtTotal;
    private javax.swing.JMenuItem mBuscar;
    // End of variables declaration//GEN-END:variables

    public JButton getJbSelecProducto() {
        return JbSelecProducto;
    }

    public void setJbSelecProducto(JButton JbSelecProducto) {
        this.JbSelecProducto = JbSelecProducto;
    }

    public JButton getJbCancela() {
        return jbCancela;
    }

    public void setJbCancela(JButton jbCancela) {
        this.jbCancela = jbCancela;
    }

    public JButton getJbConfirma() {
        return jbConfirma;
    }

    public void setJbConfirma(JButton jbConfirma) {
        this.jbConfirma = jbConfirma;
    }

    public JButton getJbSelecCliente() {
        return jbSelecCliente;
    }

    public void setJbSelecCliente(JButton jbSelecCliente) {
        this.jbSelecCliente = jbSelecCliente;
    }

    public String getJlCliente() {
        return jlCliente.getText();
    }

    public void setJlCliente(String cliente) {
        this.jlCliente.setText(cliente);
    }

    public TableModel getJtDetalleVenta() {
        return jtDetalleVenta.getModel();
    }

    public void setJtDetalleVenta(TableModel DetalleVenta) {
        this.jtDetalleVenta.setModel(DetalleVenta);
    }

    public String getJtTotal() {
        return jtTotal.getText();
    }

    public void setJtTotal(String total) {
        this.jtTotal.setText(total);
    }

    public JFormattedTextField getFecha() {
        return Fecha;
    }

    public void setFecha(JFormattedTextField Fecha) {
        this.Fecha = Fecha;
    }

    public JFormattedTextField getNroFactura() {
        return NroFactura;
    }

    public void setNroFactura(JFormattedTextField NroFactura) {
        this.NroFactura = NroFactura;
    }

    public void setNroFactura(String valueOf) {
        this.NroFactura.setText(valueOf);
    }

    public void setFecha(String date) {
        this.Fecha.setText(date);
    }

    public JMenuItem getmBuscar() {
        return mBuscar;
    }

    public void setmBuscar(JMenuItem mBuscar) {
        this.mBuscar = mBuscar;
    }

   /* public JMenuItem getmEliminar() {
        return mEliminar;
    }

    public void setmEliminar(JMenuItem mEliminar) {
        this.mEliminar = mEliminar;
    }
    */
    
    
}
