/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PantallaRealizarPedido.java
 *
 * Created on 06-nov-2011, 21:45:38
 */
package Pantalla;

import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author duende
 */
public class PantallaRealizarPedido extends javax.swing.JInternalFrame {

    /** Creates new form PantallaRealizarPedido */
    public PantallaRealizarPedido() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtPedidos = new javax.swing.JTable();
        jbRealizarPedido = new javax.swing.JButton();
        jbRecibirPedido = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(true);

        jtPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtPedidos);

        jbRealizarPedido.setText("Consultar Pendientes");

        jbRecibirPedido.setText("Recibir Pedido");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jbRealizarPedido)
                        .addGap(69, 69, 69)
                        .addComponent(jbRecibirPedido)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbRealizarPedido)
                    .addComponent(jbRecibirPedido))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbRealizarPedido;
    private javax.swing.JButton jbRecibirPedido;
    private javax.swing.JTable jtPedidos;
    // End of variables declaration//GEN-END:variables

    public JButton getJbRealizarPedido() {
        return jbRealizarPedido;
    }

    public void setJbRealizarPedido(JButton jbRealizarPedido) {
        this.jbRealizarPedido = jbRealizarPedido;
    }

    public JTable getJtPedidos() {
        return jtPedidos;
    }

    public void setJtPedidos(JTable jtPedidos) {
        this.jtPedidos = jtPedidos;
    }

    public JButton getJbRecibirPedido() {
        return jbRecibirPedido;
    }

    public void setJbRecibirPedido(JButton jbRecibirPedido) {
        this.jbRecibirPedido = jbRecibirPedido;
    }


}
